# Override the properties for dev environment here

server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fms_utm_integration
    username: postgres
    password: my-password-1

utm:
  approval:
    dev-update-enabled: true
