ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS sync_status VARCHAR(50);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS sync_error_code VARCHAR(100);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS sync_error_message VARCHAR(1000);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS request_payload_snapshot TEXT;
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS response_payload_snapshot TEXT;
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS personal_id_number VARCHAR(100);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS license_number VARCHAR(100);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS phone_number VARCHAR(100);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS legit_verify VARCHAR(100);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS note VARCHAR(1000);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS organization_id VARCHAR(100);
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMP;
ALTER TABLE pilot_registration ADD COLUMN IF NOT EXISTS submitted_session_id VARCHAR(100);
CREATE INDEX IF NOT EXISTS idx_pilot_registration_utm_pilot_id ON pilot_registration (utm_pilot_id);
CREATE INDEX IF NOT EXISTS idx_pilot_registration_personal_id_number ON pilot_registration (personal_id_number);
CREATE INDEX IF NOT EXISTS idx_pilot_registration_license_number ON pilot_registration (license_number);

ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS sync_status VARCHAR(50);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS sync_error_code VARCHAR(100);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS sync_error_message VARCHAR(1000);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS request_payload_snapshot TEXT;
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS response_payload_snapshot TEXT;
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS serial_number VARCHAR(100);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS registration_id VARCHAR(100);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS drone_status VARCHAR(100);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS status_legit VARCHAR(100);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS status_legit_note VARCHAR(1000);
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMP;
ALTER TABLE drone_registration ADD COLUMN IF NOT EXISTS submitted_session_id VARCHAR(100);
CREATE INDEX IF NOT EXISTS idx_drone_registration_utm_drone_id ON drone_registration (utm_drone_id);
CREATE INDEX IF NOT EXISTS idx_drone_registration_serial_number ON drone_registration (serial_number);
CREATE INDEX IF NOT EXISTS idx_drone_registration_registration_id ON drone_registration (registration_id);

ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS access_token TEXT;
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS refresh_token TEXT;
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS token_type VARCHAR(100);
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS access_token_expires_at TIMESTAMP;
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS refresh_token_expires_at TIMESTAMP;
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS session_state VARCHAR(255);
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS scope VARCHAR(1000);
ALTER TABLE utm_session ADD COLUMN IF NOT EXISTS last_refresh_at TIMESTAMP;
